---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _testimonials
  label: Testimonials
  create: all
  match: "**/*"
- type: directory
  path: _team
  label: Team
  create: all
  match: "**/*"
- type: directory
  path: _services
  label: Services
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
